version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 'HasloDoRoota'   #changed
      MYSQL_DATABASE: 'budget-db'   #changed
      MYSQL_USER: 'adminek'   #changed
      MYSQL_PASSWORD: 'HasloDoAdmina'   #changed
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - db_net

networks:
  db_net:
